### PR TITLE
support for retrieving HLT cpu load from F3mon

### PR DESCRIPTION
**Pull request by andreh12**
* needed for cmsdaq/DAQExpert/issues/44
* includes a test
* `mvn test` reports: `Tests run: 44, Failures: 0, Errors: 0, Skipped: 2`
* `mvn integration-test` reports: `Tests run: 13, Failures: 0, Errors: 0, Skipped: 0`
* shares a commit with [feature/fu-crashing](https://github.com/cmsdaq/DAQAggregator/compare/dev...feature/fu-crashing?expand=1)
* still need to modify ` DAQAggregator_example.properties` so waiting for `feature/fu-crashing` to be merged (commit 0e1885e )

### CODE REVIEW

**Comment by m-gl** [comment]
feature/fu-crashing has been merged to dev

**Comment by andreh12** [comment]
rebased on current dev (c61a545), resolved conflicts with respect to branch `feature/fu-crashing`.

test reports:
* `mvn test`: `Tests run: 45, Failures: 0, Errors: 0, Skipped: 2`
* `mvn integration-test`: `Tests run: 13, Failures: 0, Errors: 0, Skipped: 0`

Ready to merge.

**Comment by andreh12** [comment]
resolved conflicts and added missing code to actually dispatch the results to the DAQ object...

`mvn test` and `mvn integration-test` do not report any failed tests

**Comment by m-gl** [comment]
Released as 1.17.8, available in dev repository. Can be used as:

```
<dependency>
	<groupId>ch.cern</groupId>
	<artifactId>DAQAggregator</artifactId>
	<version>1.17.8</version>
</dependency>
```

**Pull request merged**
